project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
    - "!archive_2425/*"
  output-dir: ../docs/2526/tutors/

website:  
  title: "MSMR"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - 00ex.qmd
      - 01ex.qmd
      - 02ex.qmd


format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


